### ISSUE TITLE
Keyboard keep showing when login with finger print.

### ISSUE THREAD

**Issue by bitcoinuser** [Blockstream/green_android#15]
Keyboard keep showing when login with finger print.

![photo4947663357486409733](https://user-images.githubusercontent.com/1178856/54849036-ca6c3900-4cc1-11e9-8c31-5ef7fc7539ed.jpg)

**Comment by domegabri** [comment]
but you can access with fingerprint right?

**Comment by bitcoinuser** [comment]
Hi, When I restored the wallet (had 2of3 wallets) that I used with greenaddress.it, before new green wallet was released, appeared the option to login with fingerprint. 
So I cleared the Green cache, data and created a new wallet. Now with this new wallet, doesn't appear the option to login with fingerprint anymore. Only appear this:

![photo4960754804351674406](https://user-images.githubusercontent.com/1178856/55079478-06651c80-507b-11e9-968e-0bdc69c2e13a.jpg)

**Comment by domegabri** [comment]
> but you can access with fingerprint right?

Yes. Using android authentication allows to login with the Android pin (+ fingerprint or pattern if you have set one). Having a keyboard is the expected behavior to have a fallback method (e.g. in case you forget the pattern).

> Now with this new wallet, doesn't appear the option to login with fingerprint anymore. 

When you restore a wallet, after scanning or typing your 24 mnemonic passphrase, you are asked to set a pin OR to use android authentication (there's a checkbox).
