### ISSUE TITLE
Locked out of wallet if trusted SPV credentials change

### ISSUE THREAD

**Issue by seth586** [Blockstream/green_android#17]
### Description

If SPV trusted node credentials change or my node goes offline, I am locked out of the wallet.

### Version

3.0.6

### Steps to reproduce

I am connected to my own node via tor. The wallet works as expected. Now turn my node off. Load green wallet. Unlock with pin. I get a spinning animation and am locked out.

### Expected behaviour

After passing the pin/pattern check I should be able to change connection options.

### Actual behaviour

The screen stays blank.

### Device or machine

Google Nexus 6 running LineageOS Android 7.1.1

**Comment by friendsofbitcoin** [comment]
> After passing the pin/pattern check I should be able to change connection options.

Yes, ideally one needs to switch back to Blockstream's server if your personal node is offline so you are never restricted from using your wallet.

Perhaps for security reasons there should be some visual icon or hint that you are no longer fully validating yourself when a full node is configured but you temporarily switched to Blockstream's server so you are aware you have lowered privacy and do not forget.

This issue is indirectly related to the problem that everyone is forced to use multisig, thus dependent upon Blockstream's server for transaction signing, wallet creation, and restoring because the 2 of 2 therefore it is critical the option of single signature is created otherwise users will not be able to use their wallet when Blockstream's server is down regardless of it being configured to use their own full node

**Comment by seth586** [comment]
This issue is not related to multisig or blockstream's server.

**Comment by domegabri** [comment]
Did you have orbot running while  logging in after node was shutdown?

**Comment by seth586** [comment]
Bingo!

So long as Orbot is connected and running, I can get access to the wallet, even if my home node is offline.

Thanks!

**Comment by greenaddress** [comment]
@seth586 This isn't because of the home node but because if you enable Tor we automatically use the greenaddress onion endpoint instead of normal

**Comment by AdamISZ** [comment]
I encounter the same issue and it's pretty frustrating scenario:

tried to use Orbot, it was almost impossible to get it to even start, for some reason, and tried to configure Green to work with it, but failed.

Now I appear to be permanently locked out of the wallet, so I don't have a way to switch the attempted Tor configuration off. Also it's kind of a problem for the user that the error just says "No connection to the internet", which is not the actual problem; the actual problem is that Tor is configured, but not working. I wouldn't have guessed this except for sifting through the github issues.
