### ISSUE TITLE
Wallet created by default is Segwit legacy

### ISSUE THREAD

**Issue by SatsCzar** [Blockstream/green_android#172]
### Description

The wallet created by default when creating a wallet in green is of the legacy segwit type, it is only possible to create a native segwit wallet if you click on the advanced options.

I believe it would be more advantageous if the default wallet was native segwit type instead of legacy segwit.

### Version

4.0.4

### Steps to reproduce

download green and create a new wallet, clicking next next next

**Comment by Xekyo** [comment]
Yeah, the native segwit account was surprisingly hard to find, even after I had reassured myself that it definitely exists. At this point most of the remaining services and wallets that cannot send to bech32 fail to do so because they are defunct: https://en.bitcoin.it/wiki/Bech32_adoption

Especially in light of recent feerate spikes, I second this suggestion.
