### ISSUE TITLE
Auto logout timeout should have option to never logout

### ISSUE THREAD

**Issue by bitcoinuser** [Blockstream/green_android#20]
Auto logout timeout should have option to never logout.

Obs. When Green is minimized and "opened" again, should always ask for fingerprint or pin.

**Comment by alessandro-saglimbeni** [comment]
Thank you for this suggestion. 

The auto-logout timer exists to improve security, which is why we didn't provide the user an endless login session.

> When Green is minimized and "opened" again, should always ask for fingerprint or pin.

This instead is to allow users to streamline some actions such as sending. Users often need to copy paste the receipient addresses from other apps, which is why they are not logged out if they complete the action within the auto-logout time.

**Comment by bitcoinuser** [comment]
Agree. But there's something annoying with the auto-logout:

If I'm using other app and green is opened and logged on background, when the auto-logout happens, the green login window show in front of the other app I'm using. 

Could be great if the auto-logout happens on background and do not show green window when I'm using other app.

**Comment by bitcoinuser** [comment]
Reopening.

**Comment by bitcoinuser** [comment]
With the option of 60 minutes implemented, I don't think it's necessary this never logout option,
