### ISSUE TITLE
F-Droid version many months behind

### ISSUE THREAD

**Issue by xmready** [Blockstream/green_android#202]
First off, I truly appreciate that Green is one of the only Bitcoin wallets to be made available in F-Droid. Considering that F-Droid offers an alternative to controlling app stores, It seems logical for Bitcoin developers to make more use of it.

What I do not understand with Green, is that the app version is soo far behind on F-Droid. The other apps I use there seem to update quickly with the new versions whether, it's on the F-Droid repos or self-hosted repos.

Can someone explain why this isn't more of a priority to get updated stable releases on one of the only FOSS app stores out there?

**Comment by angelix** [comment]
Thank you for raising this important issue. There are several reasons why updates for the Green wallet on F-Droid can be delayed:

1. Build System Control:
We can't fully control the F-Droid build system. Sometimes, building the Green Development Kit (GDK) is broken due to bugs in upstream libraries, causing delays.

2. Dependencies:
We had to create a separate F-Droid version of Green without Google Services and other dependencies, which takes additional time and effort.

3. Build Script Configuration:
Misconfiguration of build scripts can also lead to issues that delay updates on F-Droid.

4. F-Droid Strict Policies
F-Droid's strict policies guarantee transparency but sometimes add a lot of complexity, leading to delays in the update process.

These factors combined can slow down the process of releasing updates on F-Droid compared to other platforms. We appreciate your patience and support.

P.S. we fixed all known issues and waiting for `4.0.28` to be released in f-droid soon.
