### ISSUE TITLE
When Green is minimized and "opened" again, should always ask for fingerprint or pin.

### ISSUE THREAD

**Issue by bitcoinuser** [Blockstream/green_android#21]
When Green is minimized and "opened" again, should always ask for fingerprint or pin.

**Comment by alessandro-saglimbeni** [comment]
Thank you again for this suggestion.

You are not required to re-authenticate yourself on Green through PIN, biometric factor, 24-word menmonic, if you stop using the app for less than the auto-logout time.

This is to allow users to streamline some actions such as sending. Users often need to copy paste the receipient addresses from other apps, which is why they are not logged out if they complete the action within the auto-logout time.

**Comment by bitcoinuser** [comment]
Ok. Xiaomi phones has option to lock apps when restoring from background. I don't think this should be added by Green,
