### ISSUE TITLE
Feature request: Support for Native Segwit/Bech32

### ISSUE THREAD

**Issue by friendsofbitcoin** [Blockstream/green_android#31]
I understand that you will be adding Bech32 support for address creation in the near future. This is great to have standard but so many wallets like electrum make a critical mistake in UX. 

Despite many services upgrading to Bech32 support , there will always be laggards that do not upgrade for years as we have seen historically. Thus it would be great to generate at least one fallback SegWit-P2SH as an option for users that get an error when trying to send to a bc1 address. 

I understand there is an incentive for us not to want to support SegWit-P2SH to force businesses to upgrade but a better approach would simply be to allow the user to click a link for 'legacy segwit" that gives them the old SegWit-P2SH address and gives them a warning that the sender is using obsolete address standard and this is costing them more in tx fees when they respend.

**Comment by ndalliard** [comment]
Any updates on native segwit/bech32 support?

**Comment by grunch** [comment]
Yes please add native segwit/bech32 support?

**Comment by angelix** [comment]
Support for Singlesig and [SegWit, Legacy SegWit] account types added in version `3.7.0`

**Comment by jgriffiths** [comment]
Its worth noting that for multisig, we will jump straight to native segwit v1 via taproot rather than supporting v0 as an interim step, since taproot allows us to reduce the cost of normal spends to that of p2wpkh and makes it impossible to distinguish green txs from any other single sig cases. We will likely schedule this when the anonymity set of taproot is higher than today, according to available resources.
