### ISSUE TITLE
[Feature Request] xpubkey export

### ISSUE THREAD

**Issue by pavlenex** [Blockstream/green_android#50]
It would be great if we're able to export the xpub key from our Green Wallet.

Use Case: I'd like to add xpub key to my BTCPay Server and receive payments directly to my Green Wallet. However, if this is added it's related to #49 since merchants usually need a bit higher gap limit than regular users.

**Comment by MarioGibney** [comment]
Because Green is a multisig wallet, its outputs are slightly more complex than single sig P2PKH or P2WPKH. Each output commits to two public keys one of the user and one of the server. The server key is derived from the wallet master public key.

However the server does not monitor all the wallet addresses, thus it is not advisable to use the xpub for receiving purposes, since our servers wouldn't be able to track them.

For people who want another way to directly generate addresses without signing into the wallet as the owner, you can use watch-only mode to generate addresses, or use our permanent payment URL feature (available from the desktop app).

If you need to use it for accounting purposes you can use the app or log in using GDK directly (e.g. with a python script) to fetch a list of your transactions with their details.

**Comment by pavlenex** [comment]
Hey @MarioGibney, thanks for clearing that one up.
I'd like to connect to my btcpay node and ignore your servers, as explained in #49, does that make any difference or not?

**Comment by friendsofbitcoin** [comment]
@pavlenex  You would need to wait for single sig support which is planned for BS green

**Comment by Eskyee** [comment]
Still waiting 😹💰 🧐 we would love gap address To be solved for noobs in 2020 🍻

**Comment by Eskyee** [comment]
Increase priority please 🙌 😍

**Comment by zonetransferagent** [comment]
Coin control would be super-amazing. If it's in the CLI already, is there documentation anywhere?

**Comment by jkauffman1** [comment]
> Coin control would be super-amazing. If it's in the CLI already, is there documentation anywhere?

https://github.com/Blockstream/green_cli#manual-coin-selection-alpha---use-at-your-own-risk

**Comment by xiaoyong-wang** [comment]
Please add this feature

**Comment by domegabri** [comment]
this should be part of a new release planned for the beginning of next year

**Comment by angelix** [comment]
Implemented in 26621b0f8c852ef5422c60cc8f64bdec64d2cce5
Already included in `4.0.3`
