### ISSUE TITLE
Amount for asset is in base units

### ISSUE THREAD

**Issue by antonio-fr** [Blockstream/green_android#54]
Transfering Liquid assets (confidential assets) from liquidd to this Green wallet, the amount the token is differently displayed.
For example, I transferred to Green 1 million units of an asset I created, and it is displayed as 100000000000000. So with 8 more zeros, it looks like the usual satoshi base which is not divided.
It lacks some division to display the right amount for the tokens in the app.
The amount displayed must be the same depending of the client. And maybe the issue is in liquidd. To me, it is more likely an issue in Green.

**Comment by allenpiscitello** [comment]
This is confusing, but by design. Green displays everything at the Satoshi level. Liquid RPC calls expect everything at the BTC level (1e8).

We'll be publishing some guidelines on how to make this more clear and how to better expose this in the UI, including registering the asset in the GUI, and possibly changing Liquid Core to display the same way as Green.
