### ISSUE TITLE
Can't scan liquid address QR code from explorer

### ISSUE THREAD

**Issue by asoltys** [Blockstream/green_android#55]
When I go to "Send" the QR Scanner that comes up can't parse QR code provided for my address on the blockstream liquid explorer: https://blockstream.info/liquid/address/VJLGi6wGgprvLXf7kNodssMVRSAktD2XrLyvv5C2dy31nwzf9yfuK88MCP1Et8afjuqJnrNAHm7N5v4u

The QR code is encoding the text "bitcoin:Gy2PKSzcMGqu8qTPKGcm38hFvVghcGGxsz"

The app manages to scan it but says "Invalid address"

**Comment by alessandro-saglimbeni** [comment]
This is actually due to this issue on the Explorer side https://github.com/Blockstream/esplora/issues/117 which currently doesn't display confidential addresses. As a result you are getting the "Invalid address" error, because Green only supports sending to confidential addresses as privacy is a fundamental feature of Liquid. 

So the underlying issue here is producing a more informative error when scanning un-confidential addresses, e.g. "Invalid non-confidential address"

**Comment by asoltys** [comment]
I see, thanks for the explanation. From a UX perspective it might be nice to support sending to un-confidential addresses but just with a strong warning or confirmation dialog first to let the user know about the privacy implications.
