### ISSUE TITLE
Feature request: add watch-only login for liquid network.

### ISSUE THREAD

**Issue by bitcoinuser** [Blockstream/green_android#61]
Add watch-only login for liquid network.

**Comment by alessandro-saglimbeni** [comment]
Hi @bitcoinuser, unfortunately it is not possible to add this feature, because the Green server doesn't know the assets and their amounts like on Bitcoin, your outputs are blinded, and only you possess the keys to unblind (read decrypt) asset types and values. 

The unblinding keys are derived from your mnemonic deterministically and the mnemonic is usually protected by PIN. This means that you would need to access your mnemonic to see what you possess on your walllet, thus defeating the purpose of the watch-only itself.

**Comment by bitcoinuser** [comment]
Ok, thanks for the information,
