### ISSUE TITLE
Green wallet won't scan liquid asset from btcpayserver payment.

### ISSUE THREAD

**Issue by yilakb** [Blockstream/green_android#86]
### Description

when scan payment from green wallet with enough L-btc for a transaction fee and enough balance of ETB liquid asset to pay on btcpayserver the wallet won't recognize the asset and show insufficient balance on the wallet, it has been working fine until recent update 3.3.5. L-btc payment usdt still work from the same wallet to the same server.

### Version

3.3.5 commit f866173dc967702cfe7d46e49f86fd005296b286

### Steps to reproduce

The problem can be reproduce using this https://bti.btcpayprovider.com/apps/4YhFTYTkKwJvxyBFYtGj4Pn5QXbC/pos  

### Expected behaviour

Create an invoice to pay custom amount, upon check out if you chose usdt or L-btc will work, but the liquid asset ETB will not work even if you have the asset in the green wallet. If you need etb asset for a test I will send if adders provided 
  

### Device or machine

Tested on both android and apple the same outcome. 

### Additional info

usdt and l-btc both PRECISION - DECIMAL PLACES is 8 but  ETB PRECISION 2

**Comment by alessandro-saglimbeni** [comment]
As you say the ETB `assetid=aa775044c32a7df391902b3659f46dfe004ccb2644ce2ddc7dba31e889391caf` has precision=2 as [from the  registry](https://assets.blockstream.info/)

What's going on here, is that when generating a payment request for 0.34 ETB (in theory 0.00000034 expressed in BTC terms) with BTCPayserver, the result is a payment request for 340000.00 ETB or 0.34000000 in BTC terms, because `amount=0.34`

liquidnetwork:VJL91iQx46HqFeX8EEYasRD3NSz9CxiQULTZJ6dSkGtxCmM6VvJtHuvgCrYsE2SEpUe6V1mL5GNeb2fN?amount=0.34&assetid=aa775044c32a7df391902b3659f46dfe004ccb2644ce2ddc7dba31e889391caf

I've discussed this with MrKukks who's just opened https://github.com/btcpayserver/btcpayserver/pull/1402 to handle the Ethiopian asset precision defined in the registry.

Thanks for reporting @yilakb

**Comment by Kukks** [comment]
Issue has been fixed and merged, and will be out in the next release. :)

**Comment by yilakb** [comment]
@Kukks @alessandro-saglimbeni  awesome, thank you!
